version: '3.5'

services:
  mifosx-web-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_ENVIRONMENT_OPTIONS=--configuration production
        - BUILDER_IMAGE=node:16-alpine
        - NGINX_IMAGE=nginx:1.19.3
        - NPM_REGISTRY_URL=https://registry.npmjs.org/
        - PUPPETEER_DOWNLOAD_HOST_ARG=https://storage.googleapis.com
        - PUPPETEER_CHROMIUM_REVISION_ARG=1011831
    ports:
      - '4200:80'
    environment:
      - FINERACT_API_URLS=https://bank.phite.com.gt,https://localhost:8443      
      - FINERACT_API_URL=https://bank.phitec.com.gt:8443
      - FINERACT_API_PROVIDER=/fineract-provider/api
      - FINERACT_API_VERSION=/v1
      - FINERACT_PLATFORM_TENANT_IDENTIFIER=default
      - MIFOS_DEFAULT_LANGUAGE=es-MX
      - MIFOS_SUPPORTED_LANGUAGES=es-MX,en-US,fr-FR
